name: build-opencl

on: [push]

jobs:
  windows_opencl:
    name: opencl/release/windows
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: msys2/setup-msys2@v1
    - name: setup
      run: |
       msys2 wget https://github.com/GPUOpen-LibrariesAndSDKs/OCL-SDK/files/1406216/lightOCLSDK.zip -O amdocl.zip
       jar xf amdocl.zip 
       
    - name: build
      run: |
       echo "##[add-path]D:\a\kaktwoos-cl\kaktwoos-cl\lib\x86_64\;D:\a\kaktwoos-cl\kaktwoos-cl\include\"
       g++ -w -static -m64 -Ofast -lstdc++ .\main.c -o kaktwoos-ocl.exe -LD:\a\kaktwoos-cl\kaktwoos-cl\lib\x86_64\ -ID:\a\kaktwoos-cl\kaktwoos-cl\include\ -ID:\a\kaktwoos-cl\kaktwoos-cl\boinc\ -ID:\a\kaktwoos-cl\kaktwoos-cl\boinc\win\ -LD:\a\kaktwoos-cl\kaktwoos-cl\boinc\lib\win\ -lboinc_api -lboinc -lboinc_opencl -lOpenCL -D_WIN64 -DWIN64 -D_WIN32 -DWIN32 -DWANTED_CACTUS_HEIGHT=21
       g++ -w -static -m64 -Ofast -lstdc++ .\main-amd.c -o kaktwoos-ocl-amd.exe -LD:\a\kaktwoos-cl\kaktwoos-cl\lib\x86_64\ -ID:\a\kaktwoos-cl\kaktwoos-cl\include\ -ID:\a\kaktwoos-cl\kaktwoos-cl\boinc\ -ID:\a\kaktwoos-cl\kaktwoos-cl\boinc\win\ -LD:\a\kaktwoos-cl\kaktwoos-cl\boinc\lib\win\ -lboinc_api -lboinc -lboinc_opencl -lOpenCL -D_WIN64 -DWIN64 -D_WIN32 -DWIN32 -DWANTED_CACTUS_HEIGHT=21
       dir
       
    - uses: actions/upload-artifact@v2
      with:
       name: kaktwoos-ocl-win
       path: .\kakt*.exe

  linux_opencl:
    name: opencl/release/linux
    runs-on: [ubuntu-latest]
    container: nvidia/opencl:devel-ubuntu16.04
    steps:
    - uses: actions/checkout@v2
    - name: build
      run: |
       apt-get update && apt-get install -y \
       ocl-icd-opencl-dev g++ libboinc7 && \
       rm -rf /var/lib/apt/lists/*
       g++ -static -w -m64 -O3 -lstdc++ ./main.c -o kaktwoos-ocl -Iboinc/ -Lboinc/lib/lin -lboinc_api -lboinc -lboinc_opencl -Wl,-Bdynamic -lpthread -lOpenCL -Wl,-dynamic-linker,/lib64/ld-linux-x86-64.so.2 -DWANTED_CACTUS_HEIGHT=21
       ls -la
    - uses: actions/upload-artifact@v2
      with:
       name: kaktwoos-ocl-lin
       path: ./kaktwoos-ocl
